# Generated by Django 4.1.7 on 2023-03-20 10:06

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('social', '0005_userprofile_place'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='userprofile',
            name='followers',
        ),
    ]
